# Generated by Django 4.2.5 on 2023-09-26 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybud', '0002_topic_room_host_messgage_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messgage',
            new_name='Message',
        ),
    ]
